services:
  app:
    build: .
    ports:
      - 80:80
  db:
    image: percona:5.7
      #environment:
       # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
        #MYSQL_DATABASE: my_database
        #MYSQL_USER: jeroen
       # MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      #volumes:
        #- mysql-data:/var/lib/mysql:rw
      ports:
        - 3306:3306
  queue:
      image: redis:5-alpine
      ports:
        - 6379:6379
volumes:
  mysql-data: